manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: grassfedreeve                         # <---
      url-base: https://github.com/grassfedreeve  # <---
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: svalboard-zmk-module
      url: https://github.com/grassfedreeve/svalboard-zmk-module
      revision: trackballs
      path: modules/svalboard-zmk-module
  self:
    path: config
